subtitle: Part of the North Queensland Diocese
description: Text about my cool site
images:
#- site-feature-image.jpg








###############
# HYAS CONFIG #
###############
titleSeparator: "-"
titleAddition: "" #for home page
description: ""

images: 
- "favicon-194x194.png" #for social templates



##BROWSER CONFIG
#apple browser config
appleFullScreen: true
appleStatusColor: white
noApplePhoneLinks: true
safariBgColor: #5bbad5
#ms browSer config
msTileColor: "#2b5797"
#general config
themecolor: "#ffffff"


#head schema additional config
schemaType: "Organization"  #organisation/person
siteLinksSearchBox: false
schemaSection: "Website"

# OG AND TWITTER SITE PARAMS
#facebookAppId: # for facebook insights
twitterSite:


#SITE ALERT TEXT FOR TOP OF PAGE
alert: false
alertText: ""

#MENU LOGO
# logoPath: "header-logo.jpg"
# logoWidth: "100"  

#CONFIGURE TOP MENU BUTTON  
# menu_button_text: "Help Desk"
# menu_button_link: "https://support.powerfulwebdesign.com.au/"
# menu_button_style: "btn-warning" # bootstrap button class







# DEV TOOLS (only on hugo server)
devGrid: true
devParameters: true










##FACEBOOKEmbed EMBED
## SEE https://developers.facebook.com/docs/plugins/page-plugin/
##language set through .Site.LanguageCode
facebookEmbedName: "Saint Peter&#039;s Anglican Church, Townsville" 
facebookEmbedUrl: https://www.facebook.com/saintpeterstownsville/ 
facebookEmbedTabs: "timeline"   # tabs to render -  timeline,events,messages (comma seperated) (timeline)
facebookEmbedHideCover: false # (false)
facebookEmbedWidth: "" # #min 180px max 500px (340)
facebookEmbedHeight: "800" # The pixel height of the plugin. Min. is 70 (500)
facebookEmbedSmallHeader: false # Use the small header instead (FALSE)
facebookEmbedAdaptiveWidth: true   Try to fit inside the container width  (TRUE)
facebookEmbedHideCover: false #hide cover photo in header (FALSE)
facebookEmbedFriendsFaces: true #Show profile photos when friends like this  (TRUE)
facebookEmbedHideCTA: false #Hide the custom call to action button (if available) (FALSE)
facebookEmbedLazy: true # loading="lazy" iframe (FALSE)
